### PR TITLE
PEP8: E265 block comment should start with '# '

### PR DESCRIPTION
**Pull request by ddemidov**
I've installed [pep8](http://github.com/jcrocholl/pep8/) tool that checks python files for conformance to the style guide. This PR is the outcome.

### CODE REVIEW

**Comment by ddemidov** [comment]
I am a bit confused of why we need this fork of ev3dev-lang now that python bindings are more or less stabilized. Is it time to merge into upstream and do the work there?

**Comment by rhempel** [comment]
This is more like the standard workflow for individuals that are not core contributors to `ev3dev`, and therefore do not have push privileges in the main repo.
Once a non-core contributor has a stable tag (like we did yesterday) that would be one pull request to the reference repo - which keeps the main repo cleaner.
I am open to suggestions such as opening a development branch on the main repo for this kind of thing.

**Comment by rhempel** [comment]
Did we lose a pull request? PR43 only has one changed file...

**Comment by ddemidov** [comment]
What do you mean? PR43 says its 7 files: https://github.com/rhempel/ev3dev-lang-python/pull/43/files

**Comment by ddemidov** [comment]
> This is more like the standard workflow for individuals that are not core contributors to ev3dev, and therefore do not have push privileges in the main repo.

Ok, so I'll just make a mental note to make all python-related work through this repo, right?

**Comment by rhempel** [comment]
Ah, now I understand - I use my `ev3dev-lang` for doing work on the official `ev3dev-lang` - both repos refer to my copy of `ev3dev-lang-python` - I need to make sure I merge all the way to the master repo when we do a release of `ev3dev-lang-python`

**Pull request merged**
